name: RDP6
on: workflow_dispatch

jobs:
  build:

    runs-on: windows-latest
    timeout-minutes: 9999

    steps:

    - name: Download ngrok
      run: |
        Invoke-WebRequest https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-windows-amd64.zip -OutFile ngrok.zip
        Invoke-WebRequest https://raw.githubusercontent.com/tantanrustandi/tanRDP/main/resources/start.bat -OutFile start.bat
        Invoke-WebRequest https://downloads.vivaldi.com/stable/Vivaldi.5.3.2679.68.x64.exe -OutFile Vivaldi.5.3.2679.68.x64.exe

    - name: Extract ngrok Files
      run: Expand-Archive ngrok.zip

    - name: Connecting ngrok Account
      run: .\ngrok\ngrok.exe authtoken $Env:NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN6 }}

    - name: Enable RDP Access
      run: |
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server'-name "fDenyTSConnections" -Value 0
        Enable-NetFirewallRule -DisplayGroup "Remote Desktop"
        Set-ItemProperty -Path 'HKLM:\System\CurrentControlSet\Control\Terminal Server\WinStations\RDP-Tcp' -name "UserAuthentication" -Value 1
#        copy opera.exe C:\Users\Public\Desktop\opera.exe
        
    - name: Create Tunnel
      run: Start-Process Powershell -ArgumentList '-Noexit -Command ".\ngrok\ngrok.exe tcp 3389"'

    - name: Connect to RDP  [CPU 2 Core - 7GB Ram - 256 SSD]
      run: cmd /c start.bat

    - name: Install Winrar
#      run: cmd /c C:\Users\Public\Desktop\opera.exe opera.exe /s
      run: cmd /c Vivaldi.5.3.2679.68.x64.exe

    - name: TimeCount
      run: |
        Invoke-WebRequest https://raw.githubusercontent.com/tantanrustandi/tanRDP/main/resources/loop.ps1 -OutFile loop.ps1
        ./loop.ps1
